/**
 * Full chart of accounts for Cohen Entities — QBO replacement baseline.
 * LJC Financial gets the complete lender/operating chart; related entities
 * get operating + intercompany due-from/due-to pairs.
 */

export const FULL_CHART_OF_ACCOUNTS = [
  // ── LJC Financial (operating lender) ─────────────────────────────────────
  { entity: 'ent-ljc', number: '1000', name: 'Cash & Bank Accounts - Simmons', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1001', name: 'Cash - Lone Star Bank', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1010', name: 'Cash - Simmons Sub-Accounts (4177/4790/7036)', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1100', name: 'Undeposited Funds', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1200', name: 'Accounts Receivable', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1300', name: 'Notes Receivable', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1310', name: 'Notes Receivable - Simmons DLOC', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1350', name: 'Holdbacks - Simmons Bank', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1400', name: 'Loan Receivable', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1410', name: 'Mortgage / Servicing Escrow', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1500', name: 'REO / Property Held for Sale', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1900', name: 'Due From - GM', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1901', name: 'Due From - Justin Cohen', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1902', name: 'Due From - OMC', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1903', name: 'Due From - LJC QOF', type: 'ASSET' },
  { entity: 'ent-ljc', number: '1999', name: 'Other Assets (Opening Rollup)', type: 'ASSET' },
  { entity: 'ent-ljc', number: '2000', name: 'Accounts Payable', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2010', name: 'Credit Card - American Express', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2011', name: 'Credit Card - Chase', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2110', name: 'DLOC - Simmons Bank', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2999', name: 'Other Liabilities (Opening Rollup)', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2900', name: 'Due To - GM', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2901', name: 'Due To - Justin Cohen', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2902', name: 'Due To - OMC', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '2910', name: 'Due To - 4J&L Partners', type: 'LIABILITY' },
  { entity: 'ent-ljc', number: '3000', name: "Owner's Equity", type: 'EQUITY' },
  { entity: 'ent-ljc', number: '3100', name: 'Retained Earnings', type: 'EQUITY' },
  { entity: 'ent-ljc', number: '3900', name: 'Opening Balance Equity', type: 'EQUITY' },
  { entity: 'ent-ljc', number: '4000', name: 'Interest Income', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '4010', name: 'Portfolio Loan Interest Income', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '4080', name: 'Gain (Loss) on Sale of REO', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '4090', name: 'Other Income', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '4091', name: 'Uncategorized Income', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '4100', name: 'Rental Income', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '4150', name: 'REO / Property Sales', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '4200', name: 'Origination & Fee Income', type: 'REVENUE' },
  { entity: 'ent-ljc', number: '3995', name: 'QBO P&L Migration Clearing', type: 'EQUITY' },
  { entity: 'ent-ljc', number: '5000', name: 'Interest Expense', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5100', name: 'Draw & Inspection Fees', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5200', name: 'Bank Service Charges', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5300', name: 'Insurance Expense', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5400', name: 'Health Insurance', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5500', name: 'Utilities', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5600', name: 'Professional Fees', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5700', name: 'Office & Software', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5710', name: 'Computer & Internet Expenses', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5720', name: 'Donations', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5730', name: 'Dues & Subscriptions', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5740', name: 'Office Supplies', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5750', name: 'Repairs & Maintenance', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5760', name: 'Telephone Expense', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5770', name: 'Unapplied Cash Bill Payment Expense', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5800', name: 'Lending Expenses (DLOC & Warehouse)', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5801', name: 'Chargebacks & Reversals', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5910', name: 'Automobile Expense', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '5920', name: 'Commissions Paid', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '6100', name: 'Rental Property Expenses', type: 'EXPENSE' },
  { entity: 'ent-ljc', number: '6110', name: 'Fees Paid on Sale of REO', type: 'EXPENSE' },

  // ── Justin Financial LLC ─────────────────────────────────────────────────
  { entity: 'ent-justin', number: '1000', name: 'Cash & Bank Accounts', type: 'ASSET' },
  { entity: 'ent-justin', number: '1350', name: 'Rehab Holdbacks', type: 'ASSET' },
  { entity: 'ent-justin', number: '1500', name: 'Real Estate Owned', type: 'ASSET' },
  { entity: 'ent-justin', number: '1900', name: 'Due From - LJC Financial', type: 'ASSET' },
  { entity: 'ent-justin', number: '2000', name: 'Accounts Payable', type: 'LIABILITY' },
  { entity: 'ent-justin', number: '2900', name: 'Notes Payable - LJC Financial (Loans)', type: 'LIABILITY' },
  { entity: 'ent-justin', number: '2901', name: 'Due To - LJC Financial (Intercompany)', type: 'LIABILITY' },
  { entity: 'ent-justin', number: '2910', name: 'Due To - 4J&L Partners', type: 'LIABILITY' },
  { entity: 'ent-justin', number: '3000', name: "Owner's Equity", type: 'EQUITY' },
  { entity: 'ent-justin', number: '3100', name: 'Retained Earnings', type: 'EQUITY' },
  { entity: 'ent-justin', number: '3900', name: 'Opening Balance Equity', type: 'EQUITY' },
  { entity: 'ent-justin', number: '4000', name: 'Other Income', type: 'REVENUE' },
  { entity: 'ent-justin', number: '5000', name: 'Operating Expenses', type: 'EXPENSE' },

  // ── OMC Housing LLC ──────────────────────────────────────────────────────
  { entity: 'ent-omc', number: '1000', name: 'Cash & Bank Accounts', type: 'ASSET' },
  { entity: 'ent-omc', number: '1200', name: 'Accounts Receivable', type: 'ASSET' },
  { entity: 'ent-omc', number: '1300', name: 'Notes Receivable', type: 'ASSET' },
  { entity: 'ent-omc', number: '1350', name: 'Deposits & Holdbacks', type: 'ASSET' },
  { entity: 'ent-omc', number: '1500', name: 'Real Estate Owned', type: 'ASSET' },
  { entity: 'ent-omc', number: '1900', name: 'Due From - LJC Financial', type: 'ASSET' },
  { entity: 'ent-omc', number: '2000', name: 'Accounts Payable', type: 'LIABILITY' },
  { entity: 'ent-omc', number: '2011', name: 'Credit Card - Chase', type: 'LIABILITY' },
  { entity: 'ent-omc', number: '2110', name: 'Notes Payable - Banks', type: 'LIABILITY' },
  { entity: 'ent-omc', number: '2900', name: 'Due To - LJC Financial', type: 'LIABILITY' },
  { entity: 'ent-omc', number: '3000', name: "Owner's Equity", type: 'EQUITY' },
  { entity: 'ent-omc', number: '3100', name: 'Retained Earnings', type: 'EQUITY' },
  { entity: 'ent-omc', number: '3900', name: 'Opening Balance Equity', type: 'EQUITY' },
  { entity: 'ent-omc', number: '4000', name: 'Other Income', type: 'REVENUE' },
  { entity: 'ent-omc', number: '5000', name: 'Operating Expenses', type: 'EXPENSE' },

  // ── Graceful Meadows (GM) — payroll entity ───────────────────────────────
  { entity: 'ent-gm', number: '1000', name: 'Cash & Bank Accounts', type: 'ASSET' },
  { entity: 'ent-gm', number: '1210', name: 'Prepaid Expenses', type: 'ASSET' },
  { entity: 'ent-gm', number: '1500', name: 'Buildings', type: 'ASSET' },
  { entity: 'ent-gm', number: '1510', name: 'Furniture & Fixtures', type: 'ASSET' },
  { entity: 'ent-gm', number: '1900', name: 'Due From - LJC Financial', type: 'ASSET' },
  { entity: 'ent-gm', number: '2000', name: 'Accounts Payable', type: 'LIABILITY' },
  { entity: 'ent-gm', number: '2011', name: 'Credit Card - VISA', type: 'LIABILITY' },
  { entity: 'ent-gm', number: '2100', name: 'Payroll Liabilities', type: 'LIABILITY' },
  { entity: 'ent-gm', number: '2200', name: 'Loans from Shareholders', type: 'LIABILITY' },
  { entity: 'ent-gm', number: '2900', name: 'Due To - LJC Financial', type: 'LIABILITY' },
  { entity: 'ent-gm', number: '3000', name: "Owner's Equity", type: 'EQUITY' },
  { entity: 'ent-gm', number: '3100', name: 'Retained Earnings', type: 'EQUITY' },
  { entity: 'ent-gm', number: '3900', name: 'Opening Balance Equity', type: 'EQUITY' },
  { entity: 'ent-gm', number: '4000', name: 'Services Income', type: 'REVENUE' },
  { entity: 'ent-gm', number: '5000', name: 'Operating Expenses', type: 'EXPENSE' },
  { entity: 'ent-gm', number: '6000', name: 'Payroll Expense - Wages', type: 'EXPENSE' },

  // ── LJC QOF LLC ──────────────────────────────────────────────────────────
  { entity: 'ent-qof', number: '1500', name: 'Property Investments', type: 'ASSET' },
  { entity: 'ent-qof', number: '2900', name: 'Due To - LJC Financial', type: 'LIABILITY' },
  { entity: 'ent-qof', number: '3100', name: 'Retained Earnings', type: 'EQUITY' },
  { entity: 'ent-qof', number: '3900', name: 'Opening Balance Equity', type: 'EQUITY' },

  // ── 4 J & L Partners, LTD ──────────────────────────────────────────────
  { entity: 'ent-4jl', number: '1000', name: 'Cash & Bank Accounts', type: 'ASSET' },
  { entity: 'ent-4jl', number: '1410', name: 'Escrows & Reserves', type: 'ASSET' },
  { entity: 'ent-4jl', number: '1500', name: 'Building & Improvements', type: 'ASSET' },
  { entity: 'ent-4jl', number: '1900', name: 'Due From - LJC Financial', type: 'ASSET' },
  { entity: 'ent-4jl', number: '1901', name: 'Due From - Justin Financial', type: 'ASSET' },
  { entity: 'ent-4jl', number: '1999', name: 'Other Assets (Opening Rollup)', type: 'ASSET' },
  { entity: 'ent-4jl', number: '2000', name: 'Accounts Payable', type: 'LIABILITY' },
  { entity: 'ent-4jl', number: '3100', name: 'Retained Earnings / Partner Equity', type: 'EQUITY' },
  { entity: 'ent-4jl', number: '3900', name: 'Opening Balance Equity', type: 'EQUITY' },
  { entity: 'ent-4jl', number: '4000', name: 'Rental Income', type: 'REVENUE' },
  { entity: 'ent-4jl', number: '5000', name: 'Operating Expenses', type: 'EXPENSE' },
];
